/*
 * Created on 2022-05-02 ( 15:41:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.life.bean;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "MBankAcntDtlHist" ( stored in table "M_BANK_ACNT_DTL_HIST" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MBankAcntDtlHistId implements Serializable {

    private static final long serialVersionUID = 1L;

    private String     badBankCode ;
    
    private String     badAcntNo ;
    
     
}
