/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:41:58 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-02 ( 15:41:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.life.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "MBankAcntDtlHist"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MBankAcntDtlHistId.class)
@Table(name="M_BANK_ACNT_DTL_HIST")


public class MBankAcntDtlHist implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="BAD_BANK_CODE", nullable=false, length=12)
    private String     badBankCode ;

    @Id
    @Column(name="BAD_ACNT_NO", nullable=false, length=60)
    private String     badAcntNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="BAD_ACNT_NAME", length=240)
    private String     badAcntName ;

    @Column(name="BAD_IBAN_NO", length=60)
    private String     badIbanNo ;

    @Column(name="BAD_ACNT_TYPE", length=12)
    private String     badAcntType ;

    @Column(name="BAD_ACNT_BRANCH", length=240)
    private String     badAcntBranch ;

    @Column(name="BAD_MAIN_ACNT_CODE", length=12)
    private String     badMainAcntCode ;

    @Column(name="BAD_CURR_CODE", length=12)
    private String     badCurrCode ;

    @Column(name="BAD_CR_UID", nullable=false, length=12)
    private String     badCrUid ;

    @Temporal(TemporalType.DATE)
    @Column(name="BAD_CR_DT", nullable=false)
    private Date       badCrDt ;

    @Column(name="BAD_UPD_UID", length=12)
    private String     badUpdUid ;

    @Temporal(TemporalType.DATE)
    @Column(name="BAD_UPD_DT")
    private Date       badUpdDt ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



