/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:04 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-02 ( 15:42:04 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.life.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotEmpty;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "MCurrency"
 *
 * @author Raj
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Table(name = "M_CURRENCY")
@EntityListeners(AuditingEntityListener.class)
public class MCurrency implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@NotEmpty(message = "Curr code required")
	@Column(name = "CURR_CODE", nullable = false, length = 12)
	private String currCode;

	// --- ENTITY DATA FIELDS
	@Column(name = "CURR_NAME", length = 240)
	private String currName;

	@Column(name = "CURR_BL_NAME", length = 240)
	private String currBlName;

	@Column(name = "CURR_SHORT_NAME", length = 30)
	private String currShortName;

	@Column(name = "CURR_BL_SHORT_NAME", length = 30)
	private String currBlShortName;

	@Column(name = "CURR_UNIT_NAME", length = 240)
	private String currUnitName;

	@Column(name = "CURR_FMT_MASK", length = 30)
	private String currFmtMask;

	@Column(name = "CURR_DECIMAL")
	private BigDecimal currDecimal;

	@Column(name = "CURR_FREEZ_YN", length = 1)
	private String currFreezYn;

	@Column(name = "CURR_FREEZ_DT")
	private LocalDateTime currFreezDt;

	@Column(name = "CURR_CR_UID", length = 12)
	private String currCrUid;

	@CreatedDate
	@Column(name = "CURR_CR_DT")
	private LocalDateTime currCrDt;
	
	@Column(name = "CURR_UPD_UID", length = 12)
	private String currUpdUid;

	@LastModifiedDate
	@Column(name = "CURR_UPD_DT")
	private LocalDateTime currUpdDt;

	@Column(name = "CURR_LOGO", length = 240)
	private String currLogo;
	
	@Transient
	private Boolean create=false;

	// --- ENTITY LINKS ( RELATIONSHIP )
	

}
