/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:10 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-02 ( 15:42:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.life.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.maan.life.util.Constants;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "MCustomer"
 *
 * @author Thamizhazhagan Velayudham
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name = "M_CUSTOMER")
@EntityListeners(AuditingEntityListener.class)
public class MCustomer implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@NotNull(message = "Customer code is required")
	@Size(max = 12, message = "Cust code must be within 12 character")
	@Column(name = "CUST_CODE", nullable = false, length = 12)
	private String custCode;

	// --- ENTITY DATA FIELDS
	@NotNull(message = "Customer name is required")
	@Size(max = 240, message = "Customer name must be within 240 character")
	@Column(name = "CUST_NAME", nullable = false, length = 240)
	private String custName;

	@Size(max = 240, message = "Customer name bl must be within 240 character")
	@Column(name = "CUST_NAME_BL", length = 240)
	private String custNameBl;

	@Size(max = 240, message = "Customer first name must be within 240 character")
	@Column(name = "CUST_FIRST_NAME", length = 240)
	private String custFirstName;

	@Size(max = 240, message = "Customer middle name must be within 240 character")
	@Column(name = "CUST_MIDDLE_NAME", length = 240)
	private String custMiddleName;

	@Size(max = 240, message = "Customer last name must be within 240 character")
	@Column(name = "CUST_LAST_NAME", length = 240)
	private String custLastName;

	@Size(max = 12, message = "Customer tittle name must be within 12 character")
	@Column(name = "CUST_TITLE", length = 12)
	private String custTitle;

	@Size(max = 240, message = "Customer short name must be within 240 character")
	@Column(name = "CUST_SHORT_NAME", length = 240)
	private String custShortName;

	@Size(max = 60, message = "Customer short name bl must be within 60 character")
	@Column(name = "CUST_SHORT_NAME_BL", length = 60)
	private String custShortNameBl;

	@Size(max = 12, message = "Customer cc code must be within 12 character")
	@Column(name = "CUST_CC_CODE", length = 12)
	private String custCcCode;

	@Size(max = 12, message = "Customer cc type must be within 12 character")
	@Column(name = "CUST_CC_TYPE", length = 12)
	private String custCcType;

	@Size(max = 240, message = "Customer phone must be within 240 character")
	@Column(name = "CUST_PHONE", length = 240)
	private String custPhone;

	@Size(max = 240, message = "Customer phone bl must be within 240 character")
	@Column(name = "CUST_PHONE_BL", length = 240)
	private String custPhoneBl;

	@Size(max = 240, message = "Customer fax must be within 240 character")
	@Column(name = "CUST_FAX", length = 240)
	private String custFax;

	@Size(max = 240, message = "Customer fax bl must be within 240 character")
	@Column(name = "CUST_FAX_BL", length = 240)
	private String custFaxBl;

	@Size(max = 240, message = "Customer mobile no must be within 240 character")
	@Column(name = "CUST_MOBILE_NO", length = 240)
	private String custMobileNo;

	@Size(max = 240, message = "Customer mobile no bl must be within 240 character")
	@Column(name = "CUST_MOBILE_NO_BL", length = 240)
	private String custMobileNoBl;

	@Size(max = 1, message = "Customer mailing address must be within 1 character")
	@Column(name = "CUST_MAILING_ADDR", length = 1)
	private String custMailingAddr;

	@Size(max = 240, message = "Customer address01 must be within 240 character")
	@Column(name = "CUST_ADDR_01", length = 240)
	private String custAddr01;

	@Size(max = 240, message = "Customer address01 bl must be within 240 character")
	@Column(name = "CUST_ADDR_01_BL", length = 240)
	private String custAddr01Bl;

	@Size(max = 240, message = "Customer address02 must be within 240 character")
	@Column(name = "CUST_ADDR_02", length = 240)
	private String custAddr02;

	@Size(max = 240, message = "Customer address02 bl must be within 240 character")
	@Column(name = "CUST_ADDR_02_BL", length = 240)
	private String custAddr02Bl;

	@Size(max = 240, message = "Customer address03 must be within 240 character")
	@Column(name = "CUST_ADDR_03", length = 240)
	private String custAddr03;

	@Size(max = 240, message = "Customer address03 bl must be within 240 character")
	@Column(name = "CUST_ADDR_03_BL", length = 240)
	private String custAddr03Bl;

	@Size(max = 12, message = "Customer area must be within 12 character")
	@Column(name = "CUST_AREA", length = 12)
	private String custArea;

	@Size(max = 12, message = "Customer region must be within 12 character")
	@Column(name = "CUST_REGION", length = 12)
	private String custRegion;

	@Size(max = 12, message = "Customer city must be within 12 character")
	@Column(name = "CUST_CITY", length = 12)
	private String custCity;

	@Size(max = 12, message = "Customer country must be within 12 character")
	@Column(name = "CUST_COUNTRY", length = 12)
	private String custCountry;

	@Size(max = 240, message = "Customer off address01 must be within 240 character")
	@Column(name = "CUST_OFF_ADDR_01", length = 240)
	private String custOffAddr01;

	@Size(max = 240, message = "Customer off address01 bl must be within 240 character")
	@Column(name = "CUST_OFF_ADDR_01_BL", length = 240)
	private String custOffAddr01Bl;

	@Size(max = 240, message = "Customer off address02 must be within 240 character")
	@Column(name = "CUST_OFF_ADDR_02", length = 240)
	private String custOffAddr02;

	@Size(max = 240, message = "Customer off address02 bl must be within 240 character")
	@Column(name = "CUST_OFF_ADDR_02_BL", length = 240)
	private String custOffAddr02Bl;

	@Size(max = 240, message = "Customer off address03 must be within 240 character")
	@Column(name = "CUST_OFF_ADDR_03", length = 240)
	private String custOffAddr03;

	@Size(max = 240, message = "Customer off address03 bl must be within 240 character")
	@Column(name = "CUST_OFF_ADDR_03_BL", length = 240)
	private String custOffAddr03Bl;

	@Size(max = 12, message = "Customer off area must be within 12 character")
	@Column(name = "CUST_OFF_AREA", length = 12)
	private String custOffArea;

	@Size(max = 12, message = "Customer off region must be within 12 character")
	@Column(name = "CUST_OFF_REGION", length = 12)
	private String custOffRegion;

	@Size(max = 12, message = "Customer off city must be within 12 character")
	@Column(name = "CUST_OFF_CITY", length = 12)
	private String custOffCity;

	@Size(max = 12, message = "Customer off country must be within 12 character")
	@Column(name = "CUST_OFF_COUNTRY", length = 12)
	private String custOffCountry;

	@Size(max = 2000, message = "Customer email1 must be within 2000 character")
	@Column(name = "CUST_EMAIL1", length = 2000)
	private String custEmail1;

	@Size(max = 2000, message = "Customer email2 must be within 2000 character")
	@Column(name = "CUST_EMAIL2", length = 2000)
	private String custEmail2;

	@Size(max = 240, message = "Customer web site must be within 240 character")
	@Column(name = "CUST_WEB_SITE", length = 240)
	private String custWebSite;

	@Size(max = 1, message = "Customer credit chk yn must be within 1 character")
	@Column(name = "CUST_CREDIT_CHK_YN", length = 1)
	private String custCreditChkYn;

	@Column(name = "CUST_CREDIT_LIMIT")
	private BigDecimal custCreditLimit;

	@Column(name = "CUST_CREDIT_DAYS")
	private BigDecimal custCreditDays;

	@Column(name = "CUST_EFF_FM_DT")
	private Date custEffFmDt;

	@Column(name = "CUST_EFF_TO_DT")
	private Date custEffToDt;

	@Size(max = 240, message = "Customer off phone must be within 240 character")
	@Column(name = "CUST_OFF_PHONE", length = 240)
	private String custOffPhone;

	@Size(max = 240, message = "Customer off phone bl must be within 240 character")
	@Column(name = "CUST_OFF_PHONE_BL", length = 240)
	private String custOffPhoneBl;

	@Size(max = 240, message = "Customer off fax must be within 240 character")
	@Column(name = "CUST_OFF_FAX", length = 240)
	private String custOffFax;

	@Size(max = 240, message = "Customer off fax bl must be within 240 character")
	@Column(name = "CUST_OFF_FAX_BL", length = 240)
	private String custOffFaxBl;

	@Size(max = 240, message = "Customer po box must be within 240 character")
	@Column(name = "CUST_PO_BOX", length = 240)
	private String custPoBox;

	@Size(max = 240, message = "Customer off po box must be within 240 character")
	@Column(name = "CUST_OFF_PO_BOX", length = 240)
	private String custOffPoBox;

	@Size(max = 12, message = "Customer gender must be within 12 character")
	@Column(name = "CUST_GENDER", length = 12)
	private String custGender;

	@Size(max = 12, message = "Customer marital sts must be within 12 character")
	@Column(name = "CUST_MARITAL_STS", length = 12)
	private String custMaritalSts;

	@Size(max = 60, message = "Customer civil id must be within 60 character")
	@Column(name = "CUST_CIVIL_ID", length = 60)
	private String custCivilId;

	@Size(max = 12, message = "Customer nationality must be within 12 character")
	@Column(name = "CUST_NATIONALITY", length = 12)
	private String custNationality;

	@Size(max = 12, message = "Customer occ type must be within 12 character")
	@Column(name = "CUST_OCC_TYPE", length = 12)
	private String custOccType;

	@Size(max = 60, message = "Customer logo name must be within 60 character")
	@Column(name = "CUST_LOGO_NAME", length = 60)
	private String custLogoName;

	@NotNull(message = "Customer group code is required")
	@Size(max = 12, message = "Customer group code must be within 12 character")
	@Column(name = "CUST_GROUP_CODE", nullable = false, length = 12)
	private String custGroupCode;

	@Size(max = 1, message = "Customer make filter yn must be within 1 character")
	@Column(name = "CUST_MAKE_FILTER_YN", length = 1)
	private String custMakeFilterYn;

	@Size(max = 1, message = "Customer body filter yn must be within 1 character")
	@Column(name = "CUST_BODY_FILTER_YN", length = 1)
	private String custBodyFilterYn;

	@Size(max = 1, message = "Customer usage filter yn must be within 1 character")
	@Column(name = "CUST_USAGE_FILTER_YN", length = 1)
	private String custUsageFilterYn;

	@Size(max = 12, message = "Customer cyl filter yn must be within 12 character")
	@Column(name = "CUST_CYL_FILTER_YN", length = 12)
	private String custCylFilterYn;

	@Size(max = 4000, message = "Customer message must be within 4000 character")
	@Column(name = "CUST_MESSAGE", length = 4000)
	private String custMessage;

	@CreatedDate
	@JsonFormat(pattern = Constants.DATE_FORMAT_PATTERN)
	@Column(name = "CUST_CR_DT", updatable = false, nullable = false)
	private LocalDateTime custCrDt;

	@CreatedBy
	@Column(name = "CUST_CR_UID", nullable = false, updatable = false, length = 12)
	private String custCrUid;

	@LastModifiedDate
	@JsonFormat(pattern = Constants.DATE_FORMAT_PATTERN)
	@Column(name = "CUST_UPD_DT")
	private LocalDateTime custUpdDt;

	@LastModifiedBy
	@Column(name = "CUST_UPD_UID", length = 12)
	private String custUpdUid;

	@Size(max = 1, message = "Customer doc email yn must be within 1 character")
	@Column(name = "CUST_DOC_EMAIL_YN", length = 1)
	private String custDocEmailYn;

	@Size(max = 1, message = "Customer garage filter yn must be within 1 character")
	@Column(name = "CUST_GARAGE_FILTER_YN", length = 1)
	private String custGarageFilterYn;

	@Size(max = 1, message = "Customer agent pg yn must be within 1 character")
	@Column(name = "CUST_AGENT_PG_YN", length = 1)
	private String custAgentPgYn;

	@Size(max = 12, message = "Customer legal sts must be within 12 character")
	@Column(name = "CUST_LEGAL_STS", length = 12)
	private String custLegalSts;

	@Size(max = 12, message = "Customer reg sts must be within 12 character")
	@Column(name = "CUST_REG_STS", length = 12)
	private String custRegSts;

	@Size(max = 12, message = "Customer nat tran must be within 12 character")
	@Column(name = "CUST_NAT_TRAN", length = 12)
	private String custNatTran;

	@Size(max = 12, message = "Customer interface must be within 12 character")
	@Column(name = "CUST_INTERFACE", length = 12)
	private String custInterface;

	@Size(max = 12, message = "Customer risk lvl must be within 12 character")
	@Column(name = "CUST_RISK_LVL", length = 12)
	private String custRiskLvl;

	@Size(max = 12, message = "Customer risk score must be within 12 character")
	@Column(name = "CUST_RISK_SCORE", length = 12)
	private String custRiskScore;

	@Size(max = 12, message = "Customer prod code must be within 12 character")
	@Column(name = "CUST_PROD_CODE", length = 12)
	private String custProdCode;

	@Size(max = 12, message = "Customer coll code must be within 12 character")
	@Column(name = "CUST_COLL_CODE", length = 12)
	private String custCollCode;

	@Size(max = 12, message = "Customer hand code must be within 12 character")
	@Column(name = "CUST_HAND_CODE", length = 12)
	private String custHandCode;

	@Size(max = 1, message = "Customer sts must be within 1 character")
	@Column(name = "CUST_STS", length = 1)
	private String custSts;

	@Size(max = 240, message = "Customer contact must be within 240 character")
	@Column(name = "CUST_CONTACT", length = 240)
	private String custContact;

	@Size(max = 60, message = "Customer am rating must be within 60 character")
	@Column(name = "CUST_AM_RATING", length = 60)
	private String custAmRating;

	@Size(max = 60, message = "Customer sp rating must be within 60 character")
	@Column(name = "CUST_SP_RATING", length = 60)
	private String custSpRating;

	@Size(max = 12, message = "Customer retail type must be within 12 character")
	@Column(name = "CUST_RETAIL_TYPE", length = 12)
	private String custRetailType;

	@Size(max = 12, message = "Customer dflt curr code must be within 12 character")
	@Column(name = "CUST_DFLT_CURR_CODE", length = 12)
	private String custDfltCurrCode;

	@Size(max = 12, message = "Customer dflt dept code must be within 12 character")
	@Column(name = "CUST_DFLT_DEPT_CODE", length = 12)
	private String custDfltDeptCode;

	@Size(max = 12, message = "Customer dflt cost centre must be within 12 character")
	@Column(name = "CUST_DFLT_COST_CENTRE", length = 12)
	private String custDfltCostCentre;

	@Size(max = 12, message = "Customer dflt tax code must be within 12 character")
	@Column(name = "CUST_DFLT_TAX_CODE", length = 12)
	private String custDfltTaxCode;

	@Size(max = 12, message = "Customer dflt nominal code must be within 12 character")
	@Column(name = "CUST_DFLT_NOMINAL_CODE", length = 12)
	private String custDfltNominalCode;

	@Size(max = 60, message = "Customer tax ref no must be within 60 character")
	@Column(name = "CUST_TAX_REF_NO", length = 60)
	private String custTaxRefNo;

	@Size(max = 12, message = "Customer tax grp code must be within 12 character")
	@Column(name = "CUST_TAX_GRP_CODE", length = 12)
	private String custTaxGrpCode;

	@Size(max = 1, message = "Customer self billing yn must be within 1 character")
	@Column(name = "CUST_SELF_BILLING_YN", length = 1)
	private String custSelfBillingYn;

	@Size(max = 1, message = "Customer debit yn must be within 1 character")
	@Column(name = "CUST_DEBIT_YN", length = 1)
	private String custDebitYn;

	@Size(max = 60, message = "Customer comp id must be within 60 character")
	@Column(name = "CUST_COMP_ID", length = 60)
	private String custCompId;

	@Column(name = "CUST_CID_EXP_DT")
	private Date custCidExpDt;

	@Column(name = "CUST_TEMP_TO_DT")
	private Date custTempToDt;

	@Size(max = 12, message = "Customer ind class must be within 12 character")
	@Column(name = "CUST_IND_CLASS", length = 12)
	private String custIndClass;

	@Size(max = 12, message = "Customer id type must be within 12 character")
	@Column(name = "CUST_ID_TYPE", length = 12)
	private String custIdType;

	@Size(max = 12, message = "Customer prod risk score must be within 12 character")
	@Column(name = "CUST_PROD_RISK_SCORE", length = 12)
	private String custProdRiskScore;

	@Size(max = 12, message = "Customer jrsd risk score must be within 12 character")
	@Column(name = "CUST_JRSD_RISK_SCORE", length = 12)
	private String custJrsdRiskScore;

	@Size(max = 12, message = "Customer other risk score must be within 12 character")
	@Column(name = "CUST_OTHER_RISK_SCORE", length = 12)
	private String custOtherRiskScore;

	@Size(max = 12, message = "Customer tot risk score must be within 12 character")
	@Column(name = "CUST_TOT_RISK_SCORE", length = 12)
	private String custTotRiskScore;

	@Size(max = 12, message = "Customer intf risk score must be within 12 character")
	@Column(name = "CUST_INTF_RISK_SCORE", length = 12)
	private String custIntfRiskScore;

	@Size(max = 12, message = "Customer aml class must be within 12 character")
	@Column(name = "CUST_AML_CLASS", length = 12)
	private String custAmlClass;

	@Size(max = 12, message = "Customer rcon period must be within 12 character")
	@Column(name = "CUST_RCON_PERIOD", length = 12)
	private String custRconPeriod;

	@Size(max = 1, message = "Customer cnst must be within 1 character")
	@Column(name = "CUST_CNST", length = 1)
	private String custCnst;

	@Size(max = 240, message = "Customer contact mobile must be within 240 character")
	@Column(name = "CUST_CONTACT_MOBILE", length = 240)
	private String custContactMobile;

	@Size(max = 240, message = "Customer contact email must be within 240 character")
	@Column(name = "CUST_CONTACT_EMAIL", length = 240)
	private String custContactEmail;

	@Size(max = 12, message = "Customer risk score ordn must be within 12 character")
	@Column(name = "CUST_RISK_SCORE_ORDN", length = 12)
	private String custRiskScoreOrdn;

	@Size(max = 12, message = "Customer prod risk score ordn must be within 12 character")
	@Column(name = "CUST_PROD_RISK_SCORE_ORDN", length = 12)
	private String custProdRiskScoreOrdn;

	@Size(max = 12, message = "Customer jrsd risk score ordn must be within 12 character")
	@Column(name = "CUST_JRSD_RISK_SCORE_ORDN", length = 12)
	private String custJrsdRiskScoreOrdn;

	@Size(max = 12, message = "Customer intf risk score ordn must be within 12 character")
	@Column(name = "CUST_INTF_RISK_SCORE_ORDN", length = 12)
	private String custIntfRiskScoreOrdn;

	@Size(max = 12, message = "Customer other risk score ordn must be within 12 character")
	@Column(name = "CUST_OTHER_RISK_SCORE_ORDN", length = 12)
	private String custOtherRiskScoreOrdn;

	@Size(max = 12, message = "Customer tot risk score ordn must be within 12 character")
	@Column(name = "CUST_TOT_RISK_SCORE_ORDN", length = 12)
	private String custTotRiskScoreOrdn;

	@Size(max = 2000, message = "Customer compl remarks must be within 2000 character")
	@Column(name = "CUST_COMPL_REMARKS", length = 2000)
	private String custComplRemarks;

	@Size(max = 240, message = "Customer sign compl prsn name must be within 240 character")
	@Column(name = "CUST_SIGN_COMPL_PRSN_NAME", length = 240)
	private String custSignComplPrsnName;

	@Size(max = 3, message = "Customer related party tran must be within 3 character")
	@Column(name = "CUST_RELATED_PARTY_TRAN", length = 3)
	private String custRelatedPartyTran;

	@Size(max = 240, message = "Customer lic issu authr must be within 240 character")
	@Column(name = "CUST_LIC_ISSU_AUTHR", length = 240)
	private String custLicIssuAuthr;

	@Size(max = 60, message = "Customer civil id uw  must be within 60 character")
	@Column(name = "CUST_CIVIL_ID_UW", length = 60)
	private String custCivilIdUw;

	@Size(max = 240, message = "Customer contact fin must be within 240 character")
	@Column(name = "CUST_CONTAC_FIN", length = 240)
	private String custContacFin;

	@Size(max = 240, message = "Customer email id fin must be within 240 character")
	@Column(name = "CUST_EMAIL_ID_FIN", length = 240)
	private String custEmailIdFin;

	@Size(max = 240, message = "Customer mobile fin must be within 240 character")
	@Column(name = "CUST_MOBILE_FIN", length = 240)
	private String custMobileFin;

	@Size(max = 240, message = "Customer civil id fin must be within 240 character")
	@Column(name = "CUST_CIVIL_ID_FIN", length = 240)
	private String custCivilIdFin;

	@Size(max = 240, message = "Customer name arabic must be within 240 character")
	@Column(name = "CUST_NAME_ARABIC", length = 240)
	private String custNameArabic;

	@Column(name = "CUST_DOB")
	private Date custDob;
}
