/*
 * Created on 2022-05-02 ( 15:42:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.life.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Composite primary key for entity "MDepartment" ( stored in table
 * "M_DEPARTMENT" )
 *
 * @author Thamizhazhagan Velayudham
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MDepartmentId implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY KEY ATTRIBUTES
	private String deptCode;

	private String deptDivnCode;

	private String deptCompCode;

}
