/*
 * Created on 2022-05-02 ( 15:42:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.life.bean;

import java.io.Serializable;
import java.util.Date;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Composite primary key for entity "MExchangeRate" ( stored in table
 * "M_EXCHANGE_RATE" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MExchangeRateId implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY KEY ATTRIBUTES
	private Date erEffFrmDt;

	private Date erEffToDt;

	private String erConvFmCurrCode;

	private String erConvToCurrCode;

	private String erRateFor;

}
