/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:12 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-02 ( 15:42:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.life.bean;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:13 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-02 ( 15:42:13 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.maan.life.util.Constants;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "MGlAccountComp"
 *
 * @author Sathish Subramani
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@EntityListeners(AuditingEntityListener.class)
@Table(name = "M_GL_ACCOUNT_COMP")
public class MGlAccountComp implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@NotNull(message = "Acomp main acnt code required")
	@Size(max = 12, message = "Acomp main acnt code must be within 12 character")
	@Column(name = "ACOMP_MAIN_ACNT_CODE", nullable = false, length = 12)
	private String acompMainAcntCode;

	// --- ENTITY DATA FIELDS
	@Size(max = 12, message = "Acomp comp code must be within 12 character")
	@Column(name = "ACOMP_COMP_CODE", nullable = false, length = 12)
	private String acompCompCode;

	@Size(max = 12, message = "Acomp sub acnt code must be within 12 character")
	@Column(name = "ACOMP_SUB_ACNT_CODE", length = 12)
	private String acompSubAcntCode;

	@CreatedBy
	@Size(max = 12, message = "Acomp cr uid must be within 12 character")
	@Column(name = "ACOMP_CR_UID", length = 12)
	private String acompCrUid;

	@CreatedDate
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = Constants.DATE_FORMAT_PATTERN)
	@Column(name = "ACOMP_CR_DT")
	private LocalDate acompCrDt;

	@LastModifiedBy
	@Size(max = 12, message = "Acomp upd id must be within 12 character")
	@Column(name = "ACOMP_UPD_UID", length = 12)
	private String acompUpdUid;

	@LastModifiedDate
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = Constants.DATE_FORMAT_PATTERN)
	@Column(name = "ACOMP_UPD_DT")
	private LocalDate acompUpdDt;

	@Size(max = 12, message = "Acomp divn code fm must be within 12 character")
	@Column(name = "ACOMP_DIVN_CODE_FM", nullable = false, length = 12)
	private String acompDivnCodeFm;

	@Size(max = 12, message = "Acomp divn code to must be within 12 character")
	@Column(name = "ACOMP_DIVN_CODE_TO", nullable = false, length = 12)
	private String acompDivnCodeTo;

	@Size(max = 12, message = "Acomp dept code fm must be within 12 character")
	@Column(name = "ACOMP_DEPT_CODE_FM", length = 12)
	private String acompDeptCodeFm;

	@Size(max = 12, message = "Acomp dept code to must be within 12 character")
	@Column(name = "ACOMP_DEPT_CODE_TO", length = 12)
	private String acompDeptCodeTo;

	@Transient
	private Boolean create = false;

	// --- ENTITY LINKS ( RELATIONSHIP )

}
