/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:21 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-02 ( 15:42:21 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.life.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.maan.life.util.Constants;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "MItemCatg"
 *
 * @author Rajkumar
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MItemCatgId.class)
@EntityListeners(AuditingEntityListener.class)
@Table(name = "M_ITEM_CATG")

public class MItemCatg implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@NotNull(message = "Ic comp code required")
	@Size(max = 12, message = "Ic comp code must be within 12 character")
	@Column(name = "IC_COMP_CODE", nullable = false, length = 12)
	private String icCompCode;

	@Id
	@NotNull(message = "Ic code required")
	@Size(max = 12, message = "Ic code must be within 12 character")
	@Column(name = "IC_CODE", nullable = false, length = 12)
	private String icCode;

	// --- ENTITY DATA FIELDS
	@Size(max = 240, message = "Ic desc must be within 240 character")
	@Column(name = "IC_DESC", length = 240)
	private String icDesc;

	@Size(max = 12, message = "Ic catg code must be within 12 character")
	@Column(name = "IC_CATG_CODE", length = 12)
	private String icCatgCode;

	@Size(max = 12, message = "Ic asst acnt code must be within 12 character")
	@Column(name = "IC_ASST_ACNT_CODE", length = 12)
	private String icAsstAcntCode;

	@Size(max = 12, message = "Ic prov acnt code must be within 12 character")
	@Column(name = "IC_PROV_ACNT_CODE", length = 12)
	private String icProvAcntCode;

	@Size(max = 12, message = "Ic depr acnt code must be within 12 character")
	@Column(name = "IC_DEPR_ACNT_CODE", length = 12)
	private String icDeprAcntCode;

	@Size(max = 12, message = "Ic pl acnt code must be within 12 character")
	@Column(name = "IC_PL_ACNT_CODE", length = 12)
	private String icPlAcntCode;

	@Column(name = "IC_DEPR_PERC")
	private BigDecimal icDeprPerc;

	@Size(max = 12, message = "Ic prefix must be within 12 character")
	@Column(name = "IC_PERFIX", length = 12)
	private String icPerfix;

	@Column(name = "IC_FIRST_NO")
	private BigDecimal icFirstNo;

	@Column(name = "IC_CURR_NO")
	private BigDecimal icCurrNo;

	@CreatedBy
	//@NotNull(message = "Ic cr uid required")
	@Size(max = 12, message = "Ic cr uid must be within 12 character")
	@Column(name = "IC_CR_UID", nullable = false, updatable = false, length = 12)
	private String icCrUid;

	@CreatedDate
	//@NotNull(message = "Ic cr dt required")
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = Constants.DATE_FORMAT_PATTERN)
	@Column(name = "IC_CR_DT", updatable = false, nullable = false)
	private LocalDateTime icCrDt;

	@LastModifiedBy
	@Size(max = 12, message = "Ic upd uid must be within 12 character")
	@Column(name = "IC_UPD_UID", length = 12)
	private String icUpdUid;

	@LastModifiedDate
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = Constants.DATE_FORMAT_PATTERN)
	@Column(name = "IC_UPD_DT")
	private LocalDateTime icUpdDt;

	@Size(max = 12, message = "Ic type must be within 12 character")
	@Column(name = "IC_TYPE", length = 12)
	private String icType;

	@Transient
	private Boolean create = false;

	// --- ENTITY LINKS ( RELATIONSHIP )

}
