/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:51 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-02 ( 15:42:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.life.bean;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.maan.life.util.Constants;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "MWfRoles"
 *
 * @author Kamalakannan Rameshbabu
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(MWfRolesId.class)
@Table(name = "M_WF_ROLES")
@EntityListeners(AuditingEntityListener.class)

public class MWfRoles implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@NotNull(message = "Wr role id is required")
	@Size(max = 12, message = "Wr role id must be within 12 character")
	@Column(name = "WR_ROLE_ID", nullable = false, length = 12)
	private String wrRoleId;

	@Id
	@NotNull(message = "Wr work step code is required")
	@Size(max = 12, message = "Wr work step code must be within 12 character")
	@Column(name = "WR_WORK_STEP_CODE", nullable = false, length = 12)
	private String wrWorkStepCode;

	@Id
	@NotNull(message = "Wr wf code is required")
	@Size(max = 12, message = "Wr wf code must be within 12 character")
	@Column(name = "WR_WF_CODE", nullable = false, length = 12)
	private String wrWfCode;

	// --- ENTITY DATA FIELDS
	@Size(max = 12, message = "Wr appr type must be within 12 character")
	@Column(name = "WR_APPR_TYPE", nullable = false, length = 12)
	private String wrApprType;

	@Column(name = "WR_LIMIT")
	private BigDecimal wrLimit;

	@Size(max = 12, message = "Wr auth role id must be within 12 character")
	@Column(name = "WR_AUTH_ROLE_ID", length = 12)
	private String wrAuthRoleId;

	@Size(max = 12, message = "Wr auth level1 must be within 12 character")
	@Column(name = "WR_AUTH_LEVEL_1", length = 12)
	private String wrAuthLevel1;

	@Size(max = 12, message = "Wr auth level2 must be within 12 character")
	@Column(name = "WR_AUTH_LEVEL_2", length = 12)
	private String wrAuthLevel2;

	@Size(max = 12, message = "Wr auth level3 must be within 12 character")
	@Column(name = "WR_AUTH_LEVEL_3", length = 12)
	private String wrAuthLevel3;

	@Size(max = 12, message = "Wr auth level4 must be within 12 character")
	@Column(name = "WR_AUTH_LEVEL_4", length = 12)
	private String wrAuthLevel4;

	@Size(max = 12, message = "Wr auth level5 must be within 12 character")
	@Column(name = "WR_AUTH_LEVEL_5", length = 12)
	private String wrAuthLevel5;

	@Size(max = 12, message = "Wr inform role id must be within 12 character")
	@Column(name = "WR_INFORM_ROLE_ID", length = 12)
	private String wrInformRoleId;

	@Size(max = 12, message = "Wr auto fwd freq must be within 12 character")
	@Column(name = "WR_AUTO_FWD_FREQ", length = 12)
	private String wrAutoFwdFreq;

	@Column(name = "WR_AUTO_FWD_TIME")
	private BigDecimal wrAutoFwdTime;

	@Size(max = 12, message = "Wr auto fwd role id must be within 12 character")
	@Column(name = "WR_AUTO_FWD_ROLE_ID", length = 12)
	private String wrAutoFwdRoleId;

	@Size(max = 1, message = "Wr email yn must be within 1 character")
	@Column(name = "WR_EMAIL_YN", length = 1)
	private String wrEmailYn;

	@Size(max = 1, message = "Wr sms yn must be within 1 character")
	@Column(name = "WR_SMS_YN", length = 1)
	private String wrSmsYn;

	@CreatedBy
	@Size(max = 12, message = "Wr cr uid must be within 12 character")
	@Column(name = "WR_CR_UID", nullable = false, length = 12, updatable = false)
	private String wrCrUid;

	@CreatedDate
	@JsonFormat(pattern = Constants.DATE_FORMAT_PATTERN)
	@Column(name = "WR_CR_DT", nullable = false, updatable = false)
	private LocalDateTime wrCrDt;

	@LastModifiedBy
	@Size(max = 12, message = "Wr upd uid must be within 12 character")
	@Column(name = "WR_UPD_UID", length = 12)
	private String wrUpdUid;

	@LastModifiedDate
	@JsonFormat(pattern = Constants.DATE_FORMAT_PATTERN)
	@Column(name = "WR_UPD_DT")
	private LocalDateTime wrUpdDt;

	// --- ENTITY LINKS ( RELATIONSHIP )

}
