/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:43:03 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-02 ( 15:43:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.life.bean;

import java.io.Serializable;
import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityListeners;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * Domain class for entity "WCustRiskCalc"
 *
 * @author Sathish Subramani Tools Generator
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@EntityListeners(AuditingEntityListener.class)
@Table(name = "W_CUST_RISK_CALC")
public class WCustRiskCalc implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@NotNull(message = "Rc cust code required")
	@Size(max = 12, message = "Rc cust code must be within 12 character")
	@Column(name = "RC_CUST_CODE", nullable = false, length = 12)
	private String rcCustCode;

	// --- ENTITY DATA FIELDS
	@Column(name = "RC_SR_NO")
	private BigDecimal rcSrNo;

	@Size(max = 2000, message = "Rc cust type must be within 2000 character")
	@Column(name = "RC_CUST_TYPE", length = 2000)
	private String rcCustType;

	@Size(max = 2000, message = "Rc interface must be within 2000 character")
	@Column(name = "RC_INTERFACE", length = 2000)
	private String rcInterface;

	@Size(max = 2000, message = "Rc product type must be within 2000 character")
	@Column(name = "RC_PRODUCT_TYPE", length = 2000)
	private String rcProductType;

	@Size(max = 2000, message = "Rc jurisdiction must be within 2000 character")
	@Column(name = "RC_JURISDICTION", length = 2000)
	private String rcJurisdiction;

	@Size(max = 2000, message = "Rc other must be within 2000 character")
	@Column(name = "RC_OTHER", length = 2000)
	private String rcOther;

	@Column(name = "RC_CUST_TYP_RI_SCR")
	private BigDecimal rcCustTypRiScr;

	@Column(name = "RC_INTER_RI_SCR")
	private BigDecimal rcInterRiScr;

	@Column(name = "RC_PRD_TYP_RI_SCR")
	private BigDecimal rcPrdTypRiScr;

	@Column(name = "RC_JURIS_RI_SCR")
	private BigDecimal rcJurisRiScr;

	@Column(name = "RC_OTHER_RI_SCR")
	private BigDecimal rcOtherRiScr;

	@Column(name = "RC_OVER_ALL_RI_SCR")
	private BigDecimal rcOverAllRiScr;

	@Size(max = 10, message = "Rc ovr all ri rate int must be within 10 character")
	@Column(name = "RC_OVR_ALL_RI_RATE_INT", length = 10)
	private String rcOvrAllRiRateInt;

	@Size(max = 5, message = "Rc sanc hi ri must be within 5 character")
	@Column(name = "RC_SANC_HI_RI", length = 5)
	private String rcSancHiRi;

	@Size(max = 5, message = "Rc breach qic risk must be within 5 character")
	@Column(name = "RC_BREACH_QIC_RISK", length = 5)
	private String rcBreachQicRisk;

	@Size(max = 10, message = "Rc ovr all ri rate must be within 10 character")
	@Column(name = "RC_OVR_ALL_RI_RATE", length = 10)
	private String rcOvrAllRiRate;

	@Column(name = "RC_UW_YEAR")
	private BigDecimal rcUwYear;

	@Size(max = 12, message = "Rc tran type must be within 12 character")
	@Column(name = "RC_TRAN_TYPE", length = 12)
	private String rcTranType;

	@Column(name = "RC_TRAN_AMNT")
	private BigDecimal rcTranAmnt;

	@Transient
	private Boolean create = false;

	// --- ENTITY LINKS ( RELATIONSHIP )

}
