/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:43:02 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-02 ( 15:43:02 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.life.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.maan.life.util.Constants;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Date;
import javax.persistence.*;

/**
 * Domain class for entity "WCustBankDtl"
 *
 * @author kamalakannan
 *
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name = "W_CUST_BANK_DTL")
@EntityListeners(AuditingEntityListener.class)

public class WCustBankDtl implements Serializable {

	private static final long serialVersionUID = 1L;

	// --- ENTITY PRIMARY KEY
	@Id
	@NotNull(message = "Cbd cust code is required")
	@Size(max = 12, message = "Cbd cust code must be within 12 character")
	@Column(name = "CBD_CUST_CODE", nullable = false, length = 12)
	private String cbdCustCode;

	// --- ENTITY DATA FIELDS
	@Size(max = 12, message = "Cbd bank code must be within 12 character")
	@Column(name = "CBD_BANK_CODE", length = 12)
	private String cbdBankCode;

	@Size(max = 12, message = "Cbd int bank code must be within 12 character")
	@Column(name = "CBD_INT_BANK_CODE", length = 12)
	private String cbdIntBankCode;

	@Size(max = 12, message = "Cbd acnt curr must be within 12 character")
	@Column(name = "CBD_ACNT_CURR", length = 12)
	private String cbdAcntCurr;

	@Size(max = 60, message = "Cbd acnt no must be within 60 character")
	@Column(name = "CBD_ACNT_NO", length = 60)
	private String cbdAcntNo;

	@Size(max = 60, message = "Cbd iban no must be within 60 character")
	@Column(name = "CBD_IBAN_NO", length = 60)
	private String cbdIbanNo;

	@Size(max = 60, message = "Cbd acnt name must be within 60 character")
	@Column(name = "CBD_ACNT_NAME", length = 60)
	private String cbdAcntName;

	@Size(max = 12, message = "Cbd swift code must be within 12 character")
	@Column(name = "CBD_SWIFT_CODE", length = 12)
	private String cbdSwiftCode;

	@Size(max = 240, message = "Cbd aba no must be within 240 character")
	@Column(name = "CBD_ABA_NO", length = 240)
	private String cbdAbaNo;

	@Size(max = 240, message = "Cbd bank addr1 must be within 240 character")
	@Column(name = "CBD_BANK_ADDR_1", length = 240)
	private String cbdBankAddr1;

	@Size(max = 240, message = "Cbd bank addr2 must be within 240 character")
	@Column(name = "CBD_BANK_ADDR_2", length = 240)
	private String cbdBankAddr2;

	@Size(max = 240, message = "Cbd remarks must be within 240 character")
	@Column(name = "CBD_REMARKS", length = 240)
	private String cbdRemarks;

	@Size(max = 1, message = "Cbd dflt yn must be within 1 character")
	@Column(name = "CBD_DFLT_YN", length = 1)
	private String cbdDfltYn;

	@CreatedBy
	@Size(max = 12, message = "Cbd cr uid must be within 12 character")
	@Column(name = "CBD_CR_UID", nullable = false, length = 12)
	private String cbdCrUid;

	@CreatedDate
	@JsonFormat(pattern = Constants.DATE_FORMAT_PATTERN)
	@Column(name = "CBD_CR_DT", nullable = false)
	private LocalDateTime cbdCrDt;

	@LastModifiedBy
	@Size(max = 12, message = "Cbd upd uid must be within 12 character")
	@Column(name = "CBD_UPD_UID", length = 12)
	private String cbdUpdUid;

	@LastModifiedDate
	@JsonFormat(pattern = Constants.DATE_FORMAT_PATTERN)
	@Column(name = "CBD_UPD_DT")
	private LocalDateTime cbdUpdDt;

	@Column(name = "CBD_SORT_CODE")
	private BigDecimal cbdSortCode;

	@Size(max = 12, message = "Cbd bank bic code must be within 12 character")
	@Column(name = "CBD_BANK_BIC_CODE", length = 12)
	private String cbdBankBicCode;

	@Size(max = 60, message = "Cbd bank add3 must be within 60 character")
	@Column(name = "CBD_BANK_ADD_3", length = 60)
	private String cbdBankAdd3;

	@Size(max = 60, message = "Cbd ifsc code must be within 60 character")
	@Column(name = "CBD_IFSC_CODE", length = 60)
	private String cbdIfscCode;

	@Size(max = 60, message = "Cbd bank name must be within 60 character")
	@Column(name = "CBD_BANK_NAME", length = 60)
	private String cbdBankName;

	// --- ENTITY LINKS ( RELATIONSHIP )

}
