/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:12 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.life.service.impl;

import java.util.Collections;
import java.util.List;
import java.util.Optional;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.maan.life.bean.MCustApplComp;
import com.maan.life.dto.ListViewParam;
import com.maan.life.repository.MCustApplCompRepository;
import com.maan.life.service.MCustApplCompService;
import com.maan.life.util.Convention;
import com.maan.life.util.ValidationUtil;

/**
 * <h2>MCustApplCompImpl</h2>
 */
@Service
@Transactional
public class MCustApplCompImpl implements MCustApplCompService {

	@Autowired
	private MCustApplCompRepository repository;

	@Autowired
	private Convention sorting;

	private Logger log = LogManager.getLogger(MCustApplCompImpl.class);

	@Override
	public List<MCustApplComp> getAll() {
		List<MCustApplComp> list = null;
		try {
			list = repository.findAll();
		} catch (Exception ex) {
			log.error("Error in getAll" + ex);
			return Collections.emptyList();
		}
		return list;
	}

	@Override
	public void saveorupdate(MCustApplComp obj) {
		repository.saveAndFlush(obj);
	}

	public Page<MCustApplComp> findAllCustApplCompDetails(ListViewParam request) {

		Pageable paging = sorting.getPaging(sorting.getPageNumber(request.getPageNumber()),
				sorting.getPageSize(request.getPageSize()));
		Page<MCustApplComp> list = null;

		if (!ValidationUtil.isNull(request.getSearch())) {
			String sear = "%" + request.getSearch() + "%";

			list = repository.findAll(sear, paging);
		} else {
			list = repository.findAll(paging);
		}
		return list;	
	}
	
	@Override
	public Optional<MCustApplComp> findById(ListViewParam request){
		return repository.findByCacmCompCodeAndCacmCustCodeAndCacmDivnCodeFmAndCacmDivnCodeToAndCacmDeptCodeFmAndCacmDeptCodeTo(request.getCode()[0],request.getCode()[1],
				request.getCode()[2],request.getCode()[3],request.getCode()[4],request.getCode()[5]);
	} 
}
