/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:12 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.life.service.impl;

import java.util.Optional;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.maan.life.bean.MGlAccountCurr;
import com.maan.life.dto.ListViewParam;
import com.maan.life.repository.MGlAccountCurrRepository;
import com.maan.life.service.MGlAccountCurrService;
import com.maan.life.util.Convention;
import com.maan.life.util.ValidationUtil;

/**
 * <h2>MGlAccountCurrServiceimpl</h2>
 */
@Service
@Transactional
public class MGlAccountCurrServiceImpl implements MGlAccountCurrService {

	@Autowired
	private MGlAccountCurrRepository repository;

	@Autowired
	private Convention sorting;

	@Override
	public void saveorupdate(MGlAccountCurr obj) {
		repository.saveAndFlush(obj);
	}

	public Page<MGlAccountCurr> findAllGlAccountCurrDetails(ListViewParam request) {

		Pageable paging = sorting.getPaging(sorting.getPageNumber(request.getPageNumber()),
				sorting.getPageSize(request.getPageSize()));
		Page<MGlAccountCurr> list = null;

		if (!ValidationUtil.isNull(request.getSearch())) {
			String sear = "%" + request.getSearch() + "%";

			list = repository.findAll(sear, paging);
		} else {
			list = repository.findAll(paging);
		}
		return list;
	}

	@Override
	public Optional<MGlAccountCurr> findById(ListViewParam request) {

		return repository.findByAcurrMainAcntCodeAndAcurrSubAcntCode(request.getCode()[0], request.getCode()[1]);

	}

}
