/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:12 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.life.service.impl;

import java.util.Optional;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.maan.life.bean.MWfRoles;
import com.maan.life.dto.ListViewParam;
import com.maan.life.repository.MWfRolesRepository;
import com.maan.life.service.MWfRolesService;
import com.maan.life.util.Convention;
import com.maan.life.util.ValidationUtil;

/**
 * <h2>MWfRolesServiceImpl</h2>
 */
@Service
@Transactional
public class MWfRolesServiceImpl implements MWfRolesService {

	@Autowired
	private MWfRolesRepository repository;

	@Autowired
	private Convention sorting;

	@Override
	public void saveorupdate(MWfRoles obj) {
		repository.saveAndFlush(obj);
	}

	public Page<MWfRoles> findAllWfRolesDetails(ListViewParam request) {

		Pageable paging = sorting.getPaging(sorting.getPageNumber(request.getPageNumber()),
				sorting.getPageSize(request.getPageSize()));
		Page<MWfRoles> list = null;

		if (!ValidationUtil.isNull(request.getSearch())) {
			String sear = "%" + request.getSearch() + "%";

			list = repository.findAll(sear, paging);
		} else {
			list = repository.findAll(paging);
		}
		return list;
	}

	@Override
	public Optional<MWfRoles> findById(ListViewParam request) {

		return repository.findByWrRoleIdAndWrWorkStepCodeAndWrWfCode(request.getCode()[0], request.getCode()[1],
				request.getCode()[2]);

	}
}
