/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:12 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.life.service.impl;

import java.util.Collections;
import java.util.List;
import java.util.Optional;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.maan.life.bean.MExchangeRate;
import com.maan.life.bean.MWfStepsApplRoles;
import com.maan.life.dto.ListViewParam;
import com.maan.life.repository.MExchangeRateRepository;
import com.maan.life.repository.MWfStepsApplRolesRepository;
import com.maan.life.service.MExchangeRateService;
import com.maan.life.service.MWfStepsApplRolesService;
import com.maan.life.util.Convention;
import com.maan.life.util.ValidationUtil;

/**
 * <h2>MWfStepsApplRolesServiceImpl</h2>
 */
@Service
@Transactional
public class MWfStepsApplRolesServiceImpl implements MWfStepsApplRolesService {

	@Autowired
	private MWfStepsApplRolesRepository repository;

	@Autowired
	private Convention sorting;

	private Logger log = LogManager.getLogger(MWfStepsApplRolesServiceImpl.class);

	/*
	 * public MExchangeRateServiceImpl(MExchangeRateRepository repo) {
	 * this.repository = repo; }
	 * 
	 * 
	 */

	@Override
	public List<MWfStepsApplRoles> getAll() {
		List<MWfStepsApplRoles> list = null;
		try {
			list = repository.findAll();
		} catch (Exception ex) {
			log.error("Error in getAll" + ex);
			return Collections.emptyList();
		}
		return list;
	}

	@Override
	public void saveorupdate(MWfStepsApplRoles obj) {
		repository.saveAndFlush(obj);
	}
	
	@Override
	public Optional<MWfStepsApplRoles> findById(ListViewParam request) {
		
		return repository.findByWsarRoleIdAndWsarWorkStepCodeAndWsarWfCode(request.getCode()[0],request.getCode()[1],request.getCode()[2]);

		
	}

	public Page<MWfStepsApplRoles> findAllWfStepsApplRolesDetails(ListViewParam request) {

		Pageable paging = sorting.getPaging(sorting.getPageNumber(request.getPageNumber()),
				sorting.getPageSize(request.getPageSize()));
		Page<MWfStepsApplRoles> list = null;

		if (!ValidationUtil.isNull(request.getSearch())) {
			String sear = "%" + request.getSearch() + "%";

			list = repository.findAll(sear,paging);
		} else {
			list = repository.findAll(paging);
		}
		return list;
	}

}
