/*
 * Java domain class for entity "MExchangeRate" 
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:12 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-05-02 ( 15:42:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.life.repository;

import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.life.bean.MCustApplComp;
import com.maan.life.bean.MCustApplCompId;
/**
 * <h2>MExchangeRateRepository</h2>
 *
 * createdAt : 2022-05-02 - Time 15:42:12
 * <p>
 * Description: "MExchangeRate" Repository
 */
public interface MCustApplCompRepository  extends JpaRepository<MCustApplComp,MCustApplCompId > , JpaSpecificationExecutor<MCustApplComp> {
	
	@Query(value = "select * from M_CUST_APPL_COMP where upper(CACM_COMP_CODE || CACM_CUST_CODE || CACM_DIVN_CODE_FM || CACM_DIVN_CODE_TO || CACM_DEPT_CODE_FM || CACM_DEPT_CODE_TO) like upper(:search) order by CACM_COMP_CODE ASC", nativeQuery = true)
	Page<MCustApplComp> findAll(String search, Pageable paging);

	Optional<MCustApplComp> findByCacmCompCodeAndCacmCustCodeAndCacmDivnCodeFmAndCacmDivnCodeToAndCacmDeptCodeFmAndCacmDeptCodeTo(
			String cacmCompCode, String cacmCustCode, String cacmDivnCodeFm, String cacmDivnCodeTo,
			String cacmDeptCodeFm, String cacmDeptCodeTo);

}
