/*

 * Java domain class for entity "MCustomer" 
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:10 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-05-02 ( 15:42:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.life.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.life.bean.MCustomer;
/**
 * <h2>MCustomerRepository</h2>
 *
 * createdAt : 2022-05-02 - Time 15:42:10
 * <p>
 * Description: "MCustomer" Repository
 */
 
 
 
public interface MCustomerRepository  extends JpaRepository<MCustomer,String > , JpaSpecificationExecutor<MCustomer> {
	
	@Query(value = "select * from M_CUSTOMER where CUST_CODE = :custCode", nativeQuery = true)
	Page<MCustomer> findByCustCode( String custCode, Pageable paging);
	
	@Query(value = "select * from M_CUSTOMER where upper( CUST_CODE || CUST_NAME || CUST_GROUP_CODE || CUST_CC_TYPE || CUST_EFF_FM_DT || CUST_EFF_TO_DT || CUST_CREDIT_LIMIT || CUST_CREDIT_DAYS ) like upper(:search)", nativeQuery = true)
	Page<MCustomer> findAll(@Param("search") String search, Pageable paging);
	
}
