/*
 * Java domain class for entity "MDepartment" 
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:11 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2022-05-02 ( 15:42:11 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.life.repository;

import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.life.bean.MDepartment;
import com.maan.life.bean.MDepartmentId;

/**
 * <h2>MDepartmentRepository</h2>
 *
 * createdAt : 2022-05-02 - Time 15:42:11
 * <p>
 * Description: "MDepartment" Repository
 */

public interface MDepartmentRepository
		extends JpaRepository<MDepartment, MDepartmentId>, JpaSpecificationExecutor<MDepartment> {

	@Query(value = "select * from M_DEPARTMENT where upper(DEPT_CODE || DEPT_NAME) like upper(:search)", nativeQuery = true)
	Page<MDepartment> findAll(String search, Pageable paging);

	Optional<MDepartment> findByDeptCode(String deptCode);

	@Query(value = "select * from M_DEPARTMENT where upper(DEPT_COMP_CODE || DEPT_DIVN_CODE || DEPT_CODE || DEPT_NAME) like upper(:search) and DEPT_COMP_CODE = :deptCompCode and DEPT_DIVN_CODE =:deptDivnCode ", nativeQuery = true)
	Page<MDepartment> findByDeptCompCodeAndDeptDivnCode(@Param("search") String search,@Param("deptCompCode") String deptCompCode, @Param("deptDivnCode") String deptDivnCode, Pageable paging);

}
