/*
 * Java domain class for entity "MExchangeRate" 
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:12 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-05-02 ( 15:42:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.life.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.life.bean.MExchangeRate;
import com.maan.life.bean.MExchangeRateId;
/**
 * <h2>MExchangeRateRepository</h2>
 *
 * createdAt : 2022-05-02 - Time 15:42:12
 * <p>
 * Description: "MExchangeRate" Repository
 */
public interface MExchangeRateRepository  extends JpaRepository<MExchangeRate,MExchangeRateId > , JpaSpecificationExecutor<MExchangeRate> {
	
	@Query(value = "select * from M_EXCHANGE_RATE where upper(ER_EFF_FRM_DT || ER_EFF_TO_DT || ER_CONV_FM_CURR_CODE || ER_CONV_TO_CURR_CODE || ER_RATE_FOR || ER_BUY_RATE) like upper(:search) order by ER_CONV_FM_CURR_CODE ASC", nativeQuery = true)
	Page<MExchangeRate> findAll(String search, Pageable paging);

}
