/*
 * Java domain class for entity "MExchangeRate" 
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:12 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2022-05-02 ( 15:42:12 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.life.repository;

import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.life.bean.MWfRoles;
import com.maan.life.bean.MWfRolesId;

/**
 * <h2>MExchangeRateRepository</h2>
 *
 * createdAt : 2022-05-02 - Time 15:42:12
 * <p>
 * Description: "MWfRolesRepository" Repository
 */
public interface MWfRolesRepository extends JpaRepository<MWfRoles, MWfRolesId>, JpaSpecificationExecutor<MWfRoles> {

	@Query(value = "select * from M_WF_ROLES where upper(WR_WORK_STEP_CODE || WR_AUTH_ROLE_ID || WR_APPR_TYPE || WR_LIMIT) like upper(:search) order by WR_WORK_STEP_CODE ASC", nativeQuery = true)
	Page<MWfRoles> findAll(String search, Pageable paging);

	Optional<MWfRoles> findByWrRoleIdAndWrWorkStepCodeAndWrWfCode(String wrRoleId, String wrWorkStepCode, String wrWfCode);

}
