/*
 * Java domain class for entity "MWfStepsApplRoles" 
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:12 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2022-05-02 ( 15:42:12 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.life.repository;

import java.util.Optional;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.maan.life.bean.MWfStepsApplRoles;
import com.maan.life.bean.MWfStepsApplRolesId;

/**
 * <h2>MWfStepsApplRolesRepository</h2>
 *
 * createdAt : 2022-05-02 - Time 15:42:12
 * <p>
 * Description: "MWfStepsApplRoles" Repository
 */
public interface MWfStepsApplRolesRepository
		extends JpaRepository<MWfStepsApplRoles, MWfStepsApplRolesId>, JpaSpecificationExecutor<MWfStepsApplRoles> {


	@Query(value = "select * from M_WF_STEPS_APPL_ROLES where upper(WSAR_ROLE_ID || WSAR_WORK_STEP_CODE || WSAR_WF_CODE) like upper(:search) order by WSAR_ROLE_ID ASC", nativeQuery = true)
	Page<MWfStepsApplRoles> findAll(@Param("search") String search, Pageable paging);

	Optional<MWfStepsApplRoles> findByWsarRoleIdAndWsarWorkStepCodeAndWsarWfCode(String wsarRoleId,String wsarWorkStepCode,String wsarWfCode);
	
	
	

	
}
