/*
 * Java domain class for entity "WCustBankDtl" 
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:12 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-05-02 ( 15:42:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.life.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.life.bean.WCustBankDtl;
/**
 * <h2>WCustBankDtlRepository</h2>
 *
 * createdAt : 2022-05-02 - Time 15:42:12
 * <p>
 * Description: "WCustBankDtlRepository" Repository
 */
public interface WCustBankDtlRepository  extends JpaRepository<WCustBankDtl,String > , JpaSpecificationExecutor<WCustBankDtl> {
	
	@Query(value = "select * from W_CUST_BANK_DTL where upper(CBD_CUST_CODE || CBD_BANK_CODE || CBD_INT_BANK_CODE || CBD_ACNT_CURR) like upper(:search) order by CBD_CUST_CODE ASC", nativeQuery = true)
	Page<WCustBankDtl> findAll(String search, Pageable paging);

}
