/*
 * Java domain class for entity "WCustRiskCalc" 
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:12 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2022-05-02 ( 15:42:12 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.life.repository;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.life.bean.WCustRiskCalc;

/**
 * <h2>WCustRiskCalcRepository</h2>
 *
 * createdAt : 2022-05-02 - Time 15:42:12
 * <p>
 * Description: "WCustRiskCalc" Repository
 */
public interface WCustRiskCalcRepository
		extends JpaRepository<WCustRiskCalc, String>, JpaSpecificationExecutor<WCustRiskCalc> {

	@Query(value = "select * from W_CUST_RISK_CALC where upper(RC_CUST_CODE || RC_SR_NO || RC_CUST_TYPE || RC_INTERFACE) like upper(:search) order by RC_CUST_CODE ASC", nativeQuery = true)
	Page<WCustRiskCalc> findAll(String search, Pageable paging);

}
