/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-05-02 ( Date ISO 2022-05-02 - Time 15:42:11 )
 * Generated by Raj Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-05-02 ( 15:42:11 )
 * Generated by Raj ( http://www.telosys.org/ ) version 3.3.0
 */

package com.maan.life.dto;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public interface MDivisionDto   {

	String getDivnCode();

	String getDivnName();

	String getDivnBaseCurrCode1();

	String getDivnBaseCurrCode2();

	String getDivnBaseCurrCode3();

	BigDecimal getDivnRoundOff();

	String getDivnUnitName();


}
